vars: {
  system-name: Threads System
}

system: ${system-name}

system <-> User: Sign up 
system <-> User: Login 
system <-> User: Logout
system <-> User: Update Profile
system <-> User: Follow/Unfollow Users
system <-> User: Create Post
system <-> User: View Feed
system <-> User: Reply Post
system <-> User: Like Post
system <-> User: View Post's comments
system <-> User: Reply to comments

