Presentation Layer: {
  React App 
}

Business Logic Layer {
  Logic {
    NodeJS Application
  } 

  Host {
    Controllers
  }

  Logic -> Host

  Infrastructure {
    DBContext
    Middlewares
    Routes
    Utils
    Socket
    Models
  }

  Host -> Infrastructure
}

Data Layer {
  MongoDB 
  Cloudinary Database
}

Presentation Layer -> Business Logic Layer: Request
Presentation Layer <- Business Logic Layer: Response 

Business Logic Layer -> Data Layer: Request
Business Logic Layer <- Data Layer: Response 
